<?php
/** @var \Mygento\Shipment\Block\Adminhtml\Order\PickupPoint $block */
?>
<?php
$points = $block->getPoints();
?>
<dl class="admin__order-shipment-methods">
    <dl class="admin__order-shipment-methods">
        <dt class="admin__order-shipment-methods-title"><?= $block->escapeHtml(__('Delivery Pickup Points')) ?>:</dt>
        <dd class="admin__order-shipment-methods-options">
            <datalist id="points" >
                <?php
                $selectedValue = '';
                $selectedName = '';
                ?>
            <?php foreach ($points as $pointKey => $pointName): ?>
                <?php
                if ($block->isPointActive($pointKey)) {
                    $selectedValue = $pointKey;
                    $selectedName = $pointName;
                }
                ?>
                <option value="<?= $block->escapeHtmlAttr($pointKey) ?>"><?= $pointName ?></option>
            <?php endforeach; ?>
            </datalist>
            <input list="points" onchange="order.setPickupPoint(this.value)" value="<?= $selectedName?>" style="width: 100%" class="input-text admin__control-text"/>
            <input type="hidden" value="<?= $selectedValue?>" name="order[estimate][pickup_point]" />
        </dd>
    </dl>
</dl>
<script>
    order.setPickupPoint = function (point) {
        var data = {};
        data['estimate[pickup_point]'] = point;
        this.loadArea([
            'shipping_method',
            'totals',
            'billing_method'
        ], true, data);
    };
</script>
